name = "politicals-ws"
compatibility_date = "2024-01-01"
main = "src/index.js"

[build]
command = "pnpm build"
pages_build_output_dir = "/dist"

[durable_objects]
bindings = [
    { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]